services:
  users:
    container_name: users-container
    build:
      context: ./users/bootloader
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - rabbitmq
  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  my-db: