services:
  users:
    container_name: users-container
    build:
      context: ./
      dockerfile: ./users/users-bootloader/Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - rabbitmq
  notifications:
    container_name: notifications-container
    build:
      context: ./
      dockerfile: ./notifications/notification-bootloader/Dockerfile
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mysql-emails
      - rabbitmq
  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql
  mysql-emails:
    image: mysql:8.0.19
    container_name: mysql-container-emails
    restart: always
    environment:
      MYSQL_DATABASE: 'email'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - my-db-email:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    restart: always
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  my-db:
  my-db-email: