services:
  users:
    container_name: users-container
    image: damiangalvan/users-bootloader:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - rabbitmq
  notifications:
    container_name: notifications-container
    image: damiangalvan/notification-bootloader:latest
    environment:
      EMAIL: 'email'
      EMAIL_PASSWORD: 'password_key'
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mysql-emails
      - rabbitmq
  posts:
    container_name: posts-container
    image: damiangalvan/posts-bootloader:latest
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - mysql-posts
      - rabbitmq
  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql
  mysql-emails:
    image: mysql:8.0.19
    container_name: mysql-container-emails
    restart: always
    environment:
      MYSQL_DATABASE: 'email'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - my-db-email:/var/lib/mysql
  mysql-posts:
    image: mysql:8.0.19
    container_name: mysql-container-posts
    restart: always
    environment:
      MYSQL_DATABASE: 'post'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - my-db-posts:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    restart: always
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  my-db:
  my-db-email:
  my-db-posts: