server:
  port: 8081
spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:mysql://mysql-emails:3306/email
    username: damian
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  rabbitmq:
    addresses: amqp://rabbitmq:5672/
    username: guest
    password: guest

