server:
  port: 8080
spring:
  application:
    name: users
  datasource:
    password: password
    url: jdbc:mysql://localhost:3308/users
    username: damian
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest